openapi: 3.0.3
info:
  title: dazblog
  description: dazBlog 是一个基于 Go 语言开发的博客系统，其目的是为了学习 Go 语言，同时也是为了学习如何开发一个完整的项目。
  version: 1.0.0
  contact: {}
servers:
- url: 127.0.0.1
- url: https://127.0.0.1
paths:
  /login:
    post:
      tags:
      - Users
      summary: login
      description: 登陆
      operationId: login
      responses:
        '200':
          description: ''
  /healthz:
    get:
      tags:
      - Users
      summary: healthz
      description: 服务器状态检查
      operationId: healthz
      responses:
        '200':
          description: ''
  /v1/users:
    get:
      tags:
      - Users
      summary: listUser
      description: 列出用户列表
      operationId: listuser
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                limit:
                  type: number
                  example: 10
                offset:
                  type: number
                  example: 0
            examples:
              listUser:
                value:
                  limit: 10
                  offset: 0
      responses:
        '200':
          description: ''
    post:
      tags:
      - Users
      summary: create
      description: 创建用户
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: daz-3ux@proton.me
                gender:
                  type: string
                  example: other
                nickname:
                  type: string
                  example: daz
                password:
                  type: string
                  example: passwd
                phone:
                  type: string
                  example: '12345678901'
                qq:
                  type: string
                  example: '123123'
                username:
                  type: string
                  example: root
            examples:
              create:
                value:
                  email: daz-3ux@proton.me
                  gender: other
                  nickname: daz
                  password: passwd
                  phone: '12345678901'
                  qq: '123123'
                  username: root
      responses:
        '200':
          description: ''
  /v1/users/root/change-password:
    put:
      tags:
      - Users
      summary: changePasswd
      description: 修改用户密码
      operationId: changepasswd
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  example: passwd
                oldPassword:
                  type: string
                  example: newpasswd
            examples:
              changePasswd:
                value:
                  newPassword: passwd
                  oldPassword: newpasswd
      responses:
        '200':
          description: ''
  /v1/posts:
    post:
      tags:
      - Posts
      summary: createPost
      description: 创建博客
      operationId: createpost
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: ttttttttttttttttttttttttest
                title:
                  type: string
                  example: test post
            examples:
              createPost:
                value:
                  content: ttttttttttttttttttttttttest
                  title: test post
      responses:
        '200':
          description: ''
    delete:
      tags:
      - Posts
      summary: deletePostCollection
      description: 批量删除博客
      operationId: deletepostcollection
      requestBody:
        content:
          application/json:
            examples:
              deletePostCollection:
                value: ''
      responses:
        '200':
          description: ''
  /v1/posts/post-23jkra:
    put:
      tags:
      - Posts
      summary: updatePost
      description: 升级博客
      operationId: updatepost
      responses:
        '200':
          description: ''
  /v1/posts/post-23adlk:
    delete:
      tags:
      - Posts
      summary: deletePost
      description: 删除博客
      operationId: deletepost
      responses:
        '200':
          description: ''
  /v1/users/root:
    get:
      tags:
      - HTTPS
      summary: catest
      description: catest
      operationId: catest
      responses:
        '200':
          description: ''
  /v1/AI:
    post:
      tags:
      - AI
      summary: Create AI
      description: Create AI
      operationId: createAi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                postID:
                  type: string
                  example: post-23hhac
                username:
                  type: string
                  example: root
            examples:
              Create AI:
                value:
                  postID: post-23hhac
                  username: root
      responses:
        '200':
          description: ''
  /v1/AI/post-23hhac:
    put:
      tags:
      - AI
      summary: updateAI
      description: updateAI
      operationId: updateai
      requestBody:
        content:
          application/json:
            examples:
              updateAI:
                value: "{\n    \"username\": \n}"
      responses:
        '200':
          description: ''
    delete:
      tags:
      - AI
      summary: deleteAI
      description: deleteAI
      operationId: deleteai
      responses:
        '200':
          description: ''
tags:
- name: Users
- name: Posts
- name: HTTPS
- name: AI

